Add local VPN IPs to Figgy's campus IPs
pulibrary/figgy pull request #4330
Opened 2020-12-01 23:11 UTC by tpendragon

The Global Protect client IPs look like these local ranges to our
servers.

2020-12-02 13:34 UTC, hackartisan approved these changes

2020-12-02 13:39 UTC, hackartisan requested changes
Shouldn't `128.112.0.0/16` cover those last 5 entries?

Can you add another comment where the new IPs came from? The current comment doesn't cover the new values and I think it will be helpful to know how we got this list.

2020-12-02 23:51 UTC, tpendragon commented
@hackartisan I updated the comment. I agree `128.112.0.0/16` covers the last few entries, but I left them in because they're copy/pasted from the KB article. Seemed better than expecting whoever looks at this is going to explode the IP ranges.

2020-12-03 14:16 UTC, hackartisan approved these changes

2020-12-03 14:17 UTC, merged