Coerce numismatics numbers to integers
pulibrary/figgy pull request #4759
Opened 2021-10-29 14:11 UTC by hackartisan

Make them optional because in at least one case there was a nil value
that raised an error.

refs #4728

2021-11-01 19:47 UTC, tpendragon requested changes

2021-11-01 19:47 UTC, tpendragon commented on app/resources/numismatics/accessions/numismatics/accession.rb
> +    attribute :accession_number, Valkyrie::Types::Coercible::Integer.optional
Question: Should we be using BetterParamsInteger for this and the other instances where we've replaced it with `Coercible::Integer.optional`?

2021-11-19 14:48 UTC, hackartisan commented
@tpendragon The other 3 properties were all using the AutoIncrementValidator, so they don't need the BetterParamsInteger. I added a comment referencing our discussion yesterday, about the possibility of using a validator for the coin_number. But I don't think we need any further code changes. Please take a look when you get a chance! Assuming it's ready, when should we run the migration?

2021-11-19 16:07 UTC, tpendragon approved these changes

2021-11-19 16:09 UTC, tpendragon commented
@hackartisan Whenever should be fine. Maybe kick it off some time today if we get this deployed?

2021-11-19 16:09 UTC, merged