Add "Rarely Used Terms" feature to Ephemera Fields
pulibrary/figgy pull request #4767
Opened 2021-11-03 18:50 UTC by tpendragon

Closes #4647

2021-11-03 18:54 UTC, tpendragon commented
Converting to draft to do some refactoring of this load_fields business.

2021-11-03 19:10 UTC, tpendragon commented
Ready for review - I think there's more refactoring that could be done in EphemeraFieldDecorator, but I'm unsure of which pattern would make the code actually more readable.

2021-11-04 13:22 UTC, hackartisan requested changes
I think it looks great. Seems clear and I don't think we need more refactoring. I made a couple of very small comments.

2021-11-04 13:22 UTC, hackartisan commented on app/resources/ephemera_fields/ephemera_field_decorator.rb
> +  def sorted_categories
Should we make these private?

2021-11-04 13:22 UTC, hackartisan commented on app/resources/ephemera_fields/ephemera_field_decorator.rb
> +  # Returns categories where favorite terms appear at the top and rarely used
So favorite terms appear in both places. It might help to add this to the comment.

2021-11-04 19:15 UTC, tpendragon commented
@hackartisan Thank you! Should be ready for re-review.

2021-11-04 20:33 UTC, hackartisan approved these changes

2021-11-04 20:33 UTC, merged