Removes duplicate flash messages in read-only mode
pulibrary/figgy pull request #4906
Opened 2022-01-21 21:44 UTC by sdellis

fixes #4799

2022-01-21 21:48 UTC, tpendragon approved these changes

2022-01-21 22:05 UTC, tpendragon commented
Looks like a couple tests failed.

2022-01-24 15:23 UTC, hackartisan requested changes

2022-01-24 15:23 UTC, hackartisan commented on app/controllers/catalog_controller.rb
> +    message << flash[:notice] if flash[:notice] && flash[:notice] != message.first
Okay this seems good but maybe we could try `&& !flash[:notice].starts_with?(message.first)` -- I think that would be a bit more flexible.

2022-01-24 20:49 UTC, hackartisan approved these changes

2022-01-24 20:49 UTC, merged