Upgrade to Ruby 2.7
pulibrary/figgy pull request #5001
Opened 2022-03-01 18:13 UTC by tpendragon

2022-03-01 23:52 UTC, tpendragon commented
Confirmed this seems to work in staging.

2022-03-02 14:29 UTC, hackartisan requested changes
This looks good. The style changes seem good. I had a couple of very small inline.

2022-03-02 14:29 UTC, hackartisan commented on app/controllers/application_controller.rb
> +    key &&= nil unless /^guest/.match?(key.to_s)
I wonder why this is preferred

2022-03-02 14:29 UTC, hackartisan commented on app/controllers/application_controller.rb
> +    key &&= nil unless /^guest/.match?(key.to_s)
answer: performance, apparently. https://www.rubydoc.info/gems/rubocop/0.47.1/RuboCop/Cop/Performance/RegexpMatch

2022-03-02 14:29 UTC, hackartisan commented on app/services/bulk_ingest_service.rb
> +        basename = File.basename(file_path)
do we need this line? It looks like we do this right before calling the method, and don't use file_path anywhere else in this method. just accept basename?

2022-03-02 14:29 UTC, hackartisan commented on config/initializers/figgy.rb
> +                            rescue
is this really indented like this?

2022-03-03 14:36 UTC, hackartisan approved these changes

2022-03-03 22:34 UTC, merged