Upgrades ordermanager to Bootstrap 4
pulibrary/figgy pull request #5142
Opened 2022-06-03 15:46 UTC by sdellis

Fixes #5126

2022-06-03 16:02 UTC, hackartisan requested changes
I think we need to rebase this PR and add back in one or more of the helpers that were removed because they weren't being used (see https://github.com/pulibrary/figgy/pull/5138/commits/db95cffccdb7aee279563ff925492a091e1fa01a)

2022-06-06 21:54 UTC, eliotjordan commented
@hackartisan Page title generation no longer uses those methods. They can be removed.

2022-06-07 14:00 UTC, sdellis commented
It looks like the coverage went down on this one. I imagine it's from adding back in the helper methods? I don't see any tests for those helper methods in the previous code. Is there any way to tell what code is not covered @hackartisan ?

2022-06-07 20:11 UTC, hackartisan approved these changes

2022-06-07 20:12 UTC, merged