Use /catalog.jsonld instead of Bibdata.
pulibrary/figgy pull request #5343
Opened 2022-08-08 21:13 UTC by tpendragon

Work towards #5229

2022-08-09 20:41 UTC, hackartisan requested changes
you re-pulled all these fixtures?

2022-08-09 20:41 UTC, hackartisan commented on app/models/processed_event.rb
> +# We need to do this because catalog provides an ongoing list of dump events,
Wait, catalog doesn't have dumps

2022-08-09 20:42 UTC, hackartisan commented
this is pretty amazing that it just drops in like that!

2022-08-09 20:53 UTC, tpendragon commented
Nope, didn't repull them, find and replace just got ahead of itself. I'll patch it later, thanks.

2022-09-08 20:38 UTC, hackartisan requested changes
This was clearly a big job, thank you for doing it.

It seems like the change of title value may be pretty noticeable to users. It looks like maybe we used to pull just the `245a` (or maybe `a` and `b`) and now we have the whole `245` including medium (`245h`) and statement of responsibility (`245c`). Given that this will then percolate out to, e.g. DPUL, I'm a little concerned this isn't what we want. How can we get assurances that this will meet user expectations? Or do we need to request an update to the json from the catalog?

2022-09-08 21:08 UTC, tpendragon commented
@hackartisan You're talking about for titles? This changed a long time ago - we just never updated our fixtures. See for instance https://bibdata.princeton.edu/bibliographic/991234563506421/jsonld

2022-09-09 13:55 UTC, hackartisan commented
Okay, great!

2022-09-09 13:55 UTC, hackartisan approved these changes

2022-09-09 13:56 UTC, merged