Allow bulk ingest of jpegs
pulibrary/figgy pull request #5484
Opened 2022-10-25 18:44 UTC by taylor-yamashita

closes #5455

2022-10-27 13:35 UTC, hackartisan reviewed
This seems right. It would be good to try bulk ingesting some jpgs in a local or staging instance to validate.

2022-11-01 15:22 UTC, tpendragon requested changes
This is a great change, but I'm not sure it will work for normal bulk ingest.

Can you try out a test like https://github.com/pulibrary/figgy/blob/eb1f6d1310279ff528094ca7d265d0a9c7126388/spec/jobs/ingest_folder_job_spec.rb#L48-L82, but for jpegs, and see where that leads you?

2022-11-01 21:41 UTC, tpendragon approved these changes
Awesome work, glad to see the test could drive the implementation.

I'm not merging because you've requested a couple other reviewers. If when you get in again this seems fine to you, you should feel free to merge it.

2022-11-01 21:41 UTC, tpendragon commented on app/services/bulk_ingest_intermediate_service.rb
> +    def extract_index(image_entry)
Renaming variables is important! Thank you!

2022-11-01 21:41 UTC, tpendragon commented on app/jobs/ingest_folder_job.rb
> +        [".tif", ".wav", ".pdf", ".zip", ".jpg"]
Good find!

2022-11-02 13:25 UTC, merged