Remove references to Cantaloupe
pulibrary/figgy pull request #5491
Opened 2022-10-28 20:39 UTC by m-ichelleliu

Resolves #4837

2022-10-28 20:41 UTC, m-ichelleliu commented
https://github.com/pulibrary/figgy/blob/c5f851aea6e7c65306e17fb40ec9cf74c40a0a7f/architecture-decisions/0007-pyramidal-tiffs.md
This document mentions that we're still using Cantaloupe as a backup. Is this up to date?

2022-10-31 19:05 UTC, eliotjordan commented
@m-ichelleliu We're no longer generating JP2s for Cantaloupe. You can remove that from the doc.

2022-10-31 19:06 UTC, eliotjordan requested changes
Looks good except for removing the line you found in the documentation.

2022-11-01 15:41 UTC, eliotjordan approved these changes

2022-11-01 15:41 UTC, merged