Add a `current` attribute to Event
pulibrary/figgy pull request #5599
Opened 2022-12-15 18:01 UTC by hackartisan

- Add `current` attribute to Event
- Mark the previous cloud_fixity Event current:false

refs #5589

2023-01-05 16:30 UTC, eliotjordan approved these changes

2023-01-05 16:40 UTC, eliotjordan requested changes
We looked at it and @hackartisan will add some more tests to the migrator spec.

2023-01-06 17:01 UTC, eliotjordan submitted a review, later dismissed

2023-01-17 21:54 UTC, hackartisan commented
migration ran on staging and here's an example of the result:
```
irb(main):012:0> a_set = events.select{ |e| e.child_id == events.last.child_id }
=> [#<Event id=#<Valkyrie::ID:0x000055aaa286c980 @id="38486005-3265-4d4b-8603-2b32f39f6c77"> internal_resource="Event" created_at="2021-11-01T21:01:02.699Z" updated_at="2021-11-01T...
irb(main):013:0> a_set.count
=> 2
irb(main):014:0> a_set.first.updated_at
=> "2021-11-01T21:01:02.699Z"
irb(main):015:0> a_set.first.current
=> true
irb(main):016:0> a_set.last.updated_at
=> "2020-10-21T21:00:55.913Z"
irb(main):017:0> a_set.last.current
=> nil
```

2023-01-17 21:55 UTC, eliotjordan approved these changes

2023-01-17 21:55 UTC, hackartisan commented
we'll merge when we're ready to deploy (after we've paused that super low queue)

2023-01-18 15:43 UTC, merged