Rescue document generation exceptions in GeoBlacklightEventGenerator
pulibrary/figgy pull request #5621
Opened 2023-01-13 21:03 UTC by eliotjordan

Closes #5551

2023-01-18 21:27 UTC, hackartisan requested changes
I want to approve this because it clearly closes the ticket in the recommended way. But I don't really understand it and I think it's confusing that the test says "when the document is invalid it's valid".  Maybe the test can spell out the use case for this functionality more specifically? In the ticket it says "This creates an error when the resource is a scanned map because GBL document attempts to build a IIIF manifest link." (that doesn't make sense to me either; why wouldn't a scanned map have a manifest?) It also might be helpful to add a comment to `errors?` since it isn't concerned with some kinds of errors -- the kind you'd have to rescue from..

2023-05-16 15:23 UTC, hackartisan requested changes
changes per discussion

2023-05-16 15:23 UTC, hackartisan commented on spec/services/event_generator/geoblacklight_event_generator_spec.rb
> +      it "is still valid" do
```suggestion
      it "is still emits a valid event" do
```

2023-05-16 15:23 UTC, hackartisan commented on app/services/event_generator/geoblacklight_event_generator.rb
> +        rescue
```suggestion
        # the resource could not generate a document at all
        rescue
```

2023-05-16 15:23 UTC, hackartisan commented on app/services/event_generator/geoblacklight_event_generator.rb
>        def errors?(record)
```suggestion
      def schema_errors?(record)
```

2023-05-23 15:52 UTC, eliotjordan commented
@hackartisan Ready for re-review.

2023-05-23 16:04 UTC, merged