Actively preserve un-preserved children.
pulibrary/figgy pull request #5651
Opened 2023-01-27 00:54 UTC by tpendragon

When preserving this now checks for children which don't have PreservationObjects and queues them up, rather than relying on it being the first time the parent was preserved.

This should fix any race conditions where that first attempt is missed, and will allow resources to preserve children on subsequent saves.

Closes #3463

2023-02-15 19:16 UTC, eliotjordan approved these changes
One suggestion, otherwise this this looks good.

2023-02-15 19:16 UTC, eliotjordan commented on app/queries/find_never_preserved_child_ids.rb
> +    resource.member_ids.select do |member_id|
suggestion: might be clearer to use `reject` rather than `select` with negative `include?`

2023-02-16 16:59 UTC, hackartisan requested changes
👍🏻 I agree with @eliotjordan; blocking for his change request.

2023-02-17 21:39 UTC, eliotjordan approved these changes

2023-02-17 21:39 UTC, merged