Fix ocr upload_file test
pulibrary/figgy pull request #5742
Opened 2023-04-07 20:01 UTC by eliotjordan

Controller tests don't like decorated `Rack::Test::UploadedFile` objects.

2023-04-07 20:04 UTC, tpendragon requested changes
Question: If Rack::Test::UploadedFile matches the API of what comes through when I use a file upload, why are we overriding what `fixture_file_upload` returns to add to that API? Were we using `fixture_file_upload` inappropriately? Should we have some other method that returns a decorated file?

2023-04-07 20:37 UTC, eliotjordan commented
Because there is limited support for Intermediate files in Figgy and they're hard to work with in tests. Good idea to change the method name.

2023-04-07 20:40 UTC, eliotjordan commented
@tpendragon Updated.

2023-04-07 20:40 UTC, tpendragon approved these changes

2023-04-10 16:53 UTC, tpendragon commented
@eliotjordan Still failing CI for some reason.

2023-04-10 18:14 UTC, eliotjordan commented
@tpendragon Missed a few includes. Ready now.

2023-04-10 18:53 UTC, tpendragon approved these changes

2023-04-10 18:53 UTC, merged