Replace webpacker with Vite
pulibrary/figgy pull request #5774
Opened 2023-04-28 15:30 UTC by hackartisan

2023-04-28 20:22 UTC, tpendragon approved these changes

2023-04-28 20:31 UTC, hackartisan reviewed
there's one change i noticed needed in the readme

2023-04-28 20:31 UTC, hackartisan commented on README.md
> +     - Or run services separately as shown in [[https://github.com/pulibrary/figgy/blob/main/Procfile.dev]]
change this -- not at .dev

2023-05-02 15:36 UTC, eliotjordan requested changes
Excellent work! Happy to finally move Figgy off of Webpacker. I just had one comment about a console.log, but otherwise it seems ready to go.

2023-05-02 17:17 UTC, eliotjordan approved these changes

2023-05-02 17:17 UTC, merged