Preserve collections
pulibrary/figgy pull request #5879
Opened 2023-06-22 16:58 UTC by tpendragon

Closes #5798

2023-06-22 18:16 UTC, eliotjordan approved these changes

2023-06-22 18:21 UTC, eliotjordan requested changes
Nice and easy. Just needs a rebase.

2023-06-22 22:50 UTC, tpendragon commented
Rebased.

2023-06-23 17:56 UTC, eliotjordan approved these changes

2023-06-23 17:56 UTC, merged