Use Selenium Standalone instead of Webdrivers
pulibrary/figgy pull request #6012
Opened 2023-10-10 19:55 UTC by tpendragon

I couldn't get selenium/webdrivers working locally, and this takes local environment out of the equation.

2023-10-13 16:15 UTC, eliotjordan requested changes
I found one small issue in the lando config, otherwsie this looks great. I'm 👍 on merging this.

2023-10-16 16:48 UTC, tpendragon commented on .lando.yml
> +        SE_NODE_OVERRIDE_MAX_SESSIONS: true
Fixed, thank you!

2023-10-16 21:06 UTC, eliotjordan approved these changes

2023-10-17 18:11 UTC, hackartisan commented
I ran on the spec/features directory and got a lot of `Net::ReadTimeout with #<Socket:(closed)>` -- maybe corresponding to the specs marked `js: true`?

2023-10-17 19:31 UTC, tpendragon commented
> I ran on the spec/features directory and got a lot of `Net::ReadTimeout with #<Socket:(closed)>` -- maybe corresponding to the specs marked `js: true`?

Interesting! Maybe we can pair at some point and look at it, these pass for me.

2023-10-18 18:06 UTC, hackartisan commented
ran the tests in parallel. I had a handful of failures like this 

```
    1.1) Failure/Error: visit user_cas_omniauth_authorize_path                                                                                                                          
                                                                                                                                                                                         
          Selenium::WebDriver::Error::ServerError:                                                                                                                                       
            status code 404                                                                                                                                                              
          # ./spec/support/features/session_helpers.rb:13:in `sign_in'                                                                                                                             # ./spec/features/numismatic_reference_spec.rb:11:in `block (2 levels) in <top (required)>'    
```

They all passed when I ran a follow-up `rspec --only-failures`

a few other failures I have related to cogeo-mosaic seem unrelated to this PR.

I'm not sure I consider this blocking at this point. maybe it's good enough.

2023-10-18 18:26 UTC, hackartisan commented
I ran in parallel again and didn't have any of those 404 failures.

2023-10-18 18:54 UTC, merged