Attaching captions ADR
pulibrary/figgy pull request #6193
Opened 2024-02-05 20:04 UTC by tpendragon

Closes #6185

2024-02-06 15:21 UTC, hackartisan requested changes
It's nice to get all these use cases here; I wonder how this documentation interacts with our attempt to collect use cases in https://github.com/pulibrary/figgy/blob/main/docs/ux/use_cases.md

This accurately reflects our decisions and is clear. I added a question and a suggestion in line.

2024-02-06 15:21 UTC, hackartisan commented on architecture-decisions/0013-captions-attach.md
> +As a researcher I want to have multiple captions each in their own language and users should be able to switch between them so that I can provide translations in addition to transcription.
Do we need something around a "default" caption? Or will captions by off by default?

2024-02-06 15:21 UTC, hackartisan commented on architecture-decisions/0013-captions-attach.md
> +1. Users will have to upload two files (the original file and the caption) if they delete a FileSet to re-upload it.
```suggestion
1. If a user deletes a FileSet they will have to upload two files (the original file and the caption) to re-create it.
```

2024-02-07 20:56 UTC, tpendragon commented
> It's nice to get all these use cases here; I wonder how this documentation interacts with our attempt to collect use cases in https://github.com/pulibrary/figgy/blob/main/docs/ux/use_cases.md

Is this a suggestion to also put them in `use_cases.md` or did you find them not useful here?

2024-02-08 19:46 UTC, hackartisan approved these changes

2024-02-12 15:37 UTC, merged