Structure Manager 2.0
pulibrary/figgy pull request #6205
Opened 2024-02-15 20:59 UTC by sdellis

2024-04-10 19:25 UTC, tpendragon requested changes
Just a small note from me. I didn't look wildly close at the structure editor Vue code, because I largely trust the tests and manual testing I've done - and I'm still sometimes confused by Vuex.

2024-04-11 14:43 UTC, sdellis commented on app/controllers/scanned_maps_controller.rb
> +    authorize! :struct_manager, @change_set.resource
In that case, I will need to change the test by removing the expectation of rendered Structure Manager html in the response. I will go ahead and do that if that's what you intended. Here's what I get from the test when I change it back to `structure`: 

```
Failure/Error: expect(response.body).to have_selector "li[data-proxy='#{file_set2.id}']"
```

2024-04-11 18:20 UTC, tpendragon commented on app/controllers/scanned_maps_controller.rb
> +    authorize! :struct_manager, @change_set.resource
I think that test should point to `struct_manager`, if it's failing then something's probably broken

2024-04-11 21:21 UTC, tpendragon approved these changes

2024-04-15 18:43 UTC, merged