Configure redis URL for health check.
pulibrary/figgy pull request #6238
Opened 2024-03-07 20:33 UTC by tpendragon

2024-03-07 21:52 UTC, hackartisan requested changes

2024-03-07 21:52 UTC, hackartisan commented on config/initializers/redis_config.rb
> +module RedisConfig
Use in sidekiq initializer?

2024-03-08 00:07 UTC, tpendragon commented on config/initializers/redis_config.rb
> +module RedisConfig
Good catch, done.

2024-03-08 15:42 UTC, eliotjordan approved these changes

2024-03-08 15:42 UTC, hackartisan approved these changes

2024-03-08 15:42 UTC, merged