Upgrade Vue and Lux
pulibrary/figgy pull request #6345
Opened 2024-04-17 15:33 UTC by eliotjordan

Closes #6249

2024-04-17 15:37 UTC, eliotjordan commented on app/javascript/entrypoints/application.js
> +const app = createApp(
Not sure if this is correct yet.

2024-04-18 20:36 UTC, sdellis commented
I had a hard time configuring vite [resolve.alias](https://vitejs.dev/config/shared-options.html#resolve-alias
). I took out the aliasing for imports and got it to work. If we want to re-implement import aliasing, we can do that in a future ticket, but it's no longer blocking the upgrade.

2024-04-25 19:53 UTC, sdellis commented
The [VueDetails](https://github.com/kim366/vue-details) dependency used in the [DirectoryPicker](https://github.com/pulibrary/figgy/blob/main/app/javascript/components/file_browser/directory_picker.vue#L8) does not work in Vue3 and has not been migrated. This is a blocker to the Vue2 -> Vue3 upgrade.

There are three ways to resolve this. 

1. [Implement using `refs`](https://stackoverflow.com/questions/77240675/vue-3-toggleevent-on-details-tag)
2. Implement locally (or fork) and [modify the render](https://github.com/kim366/vue-details/blob/master/src/index.js#L9-L15) code [so that render works in Vue3](https://stackoverflow.com/questions/65529646/why-the-render-h-function-cannot-use-component-name-directly-to-render-in-vue3-x)
3. Implement show/hide functionality without using the <details> tag and its native element state, [as in the Tree component](https://github.com/pulibrary/figgy/blob/main/app/javascript/components/Tree.vue#L117-L120).

2024-05-08 22:06 UTC, sdellis commented
Todo: The `itemLabel` field calls the `updateSingle` function `on:input`, but the item in items remains unchanged when [dispatched to the action](https://github.com/pulibrary/figgy/blob/main/app/javascript/components/OrderManagerFilesetForm.vue#L180). It should update the label/caption on every input event.

2024-05-23 18:34 UTC, hackartisan requested changes
I found a number of places where there's commented-out code that I wonder if we could just delete.

Other than that, everything looks good. There's a test failure about snapshots that should be resolved. I'm deploying to staging so we can try it out.

2024-05-23 18:34 UTC, hackartisan commented on app/javascript/test/setup.js
> +// import system from 'lux-design-system'
delete?

2024-05-23 18:48 UTC, hackartisan commented
I tried this in staging. I messed with: 
* order manager
* structure manager
* datatables
* removing / adding a child from a MVW

all worked and looked good, in one case better than prod, which was overflowing in the order manager at a moderately zoomed-in screen size.

2024-05-24 19:47 UTC, merged