Upgrade jquery-ui-rails
pulibrary/figgy pull request #6358
Opened 2024-04-19 16:43 UTC by eliotjordan

Updates jquery-ui-rails to address 4 dependabot alterts.

Meta question for later: Are we still using all of the[ jquery-ui components](https://github.com/pulibrary/figgy/blob/main/app/assets/javascripts/application.js#L27-L31)? For example, I think we're using the Lux datepicker now.

2024-04-23 20:35 UTC, hackartisan commented
How do / can we know that everything using jquery-ui stills works after this merge?

2024-04-23 20:42 UTC, hackartisan commented
It looks like it's mostly used in the (old) structure manager.

2024-04-23 20:46 UTC, hackartisan commented
I'm not sure it's working right? I just tried the structure manager on figgy-staging for this item: https://figgy-staging.princeton.edu/concern/scanned_resources/123bbbfb-4e7d-4bc6-9752-4b48925a1cdf/struct_manager

![Screenshot 2024-04-23 at 4 45 56 PM](https://github.com/pulibrary/figgy/assets/845363/e9ed67e2-fc93-4187-a95a-2c35a35fea4b)

2024-04-24 16:32 UTC, tpendragon requested changes
Old structure manager definitely breaks, and the nestedSortable plugin isn't updated for new jquery-ui. We'll have to delay this update until we remove the old structure editor.

2025-09-19 18:51 UTC, closed without merging